set nocount on;
go;
exec insertLibraryWishlistItem 'Blurred Lines','Blue Moon, Language Arts, Hamilton Shirts, Erickson, West Hill 8847, Minneapolis, SRB 1280';
exec insertLibraryWishlistItem 'Let Me Love You','Aquafina, Spanish, Lilli Ann, Metro Cash&Carry, Bury  Crossroad 4427, St. Louis, FSM 8354';
exec insertLibraryWishlistItem 'Uptown Funk!','Aquafina, Grammar, Hamilton Shirts, BuzzFeed, Queen Caroline   Drive 6811, Madrid, GMB 5536';
exec insertLibraryWishlistItem 'Andalouse','Cappy, Resource Program, Ex-Boyfriend, Biolife Grup, Blackheath   Alley 2685, Murfreesboro, GNB 7314';
exec insertLibraryWishlistItem 'Bailando','Edelweiss, Language Arts, Marchesa, It Smart Group, Besson  Crossroad 4725, Santa Ana, MAC 3404';
exec insertLibraryWishlistItem 'Listen to your heart','Frooti, Speech, Lee, Areon Impex, Coal Wharf  Grove 5258, Bridgeport, LBY 7146';
exec insertLibraryWishlistItem 'Yeah!','None';
exec insertLibraryWishlistItem 'Hero','Evian, French, Bujo, Comcast, Bayberry Walk 489, Miami, KWT 4081';
exec insertLibraryWishlistItem 'Mambo No. 5','Tanqueray, American Literature, Columbia Sportswear, Leadertech Consulting, Egerton  Alley 1176, Los Angeles, MNE 2453';
exec insertLibraryWishlistItem 'Its my life','Absolut, Ancient Civilizations, Dollie & Me, Global Print, Callcott   Hill 3274, Atlanta, HRV 7882';
exec insertLibraryWishlistItem 'Kiss Kiss','None';
exec insertLibraryWishlistItem 'I want to break free','Z Lager, Resource Program, Cross Colours, Areon Impex, Rivervalley Tunnel 4934, Anaheim, MNP 6052';
exec insertLibraryWishlistItem 'Sway','Skol, Leadership, TNT, Danone, Cecilia  Lane 9981, El Paso, YEM 8777';
exec insertLibraryWishlistItem 'Mercy ','Duvel Golden Ale, Speech, Forever 21, Leadertech Consulting, Shepherds  Pass 8482, Philadelphia, HMD 8506';
exec insertLibraryWishlistItem 'Walking on sunshine','Deep River Rock, Ecology, Forever 21, Danone, Baylis  Walk 1116, Valetta, DNK 5585';
exec insertLibraryWishlistItem 'Party Rock Anthem','SunnyD, Design and technology, DKNY, Leadertech Consulting, Bayberry Alley 6924, Tallahassee, IMN 4843';
exec insertLibraryWishlistItem 'Billionaire','None';
exec insertLibraryWishlistItem 'Cest la vie','Grolsch, Resource Program, Nice Collective, Facebook, Chamberlain  Alley 215, Tokyo, BLZ 0453';
exec insertLibraryWishlistItem 'Foolish Games','Edelweiss, Modern Literature, Guess, Facebook, Marischal  Hill 2684, Sacramento, NOR 7768';
exec insertLibraryWishlistItem 'How you remind me','Frooti, Economics, Columbia Sportswear, UPC, Bermondsey    Vale 8891, San Jose, ESP 2324';
exec insertLibraryWishlistItem 'Wake me up before you gogo','Moutai, French, Calvin Klein, AECOM, Queen Caroline   Road 2174, San Jose, KOR 8562';
exec insertLibraryWishlistItem 'Smooth','Keystone Light, German, Ex-Boyfriend, ENEL, Black Friars   Rue 5625, Seattle, FIN 0728';
exec insertLibraryWishlistItem 'Brasil','Mumm, Resource Program, Max Studio, It Smart Group, Abbey   Vale 8946, Saint Paul, SRB 2281';
exec insertLibraryWishlistItem 'Wake me up','None';
exec insertLibraryWishlistItem 'Flashdance...What A Feeling','Coca Cola, German, Hamilton Shirts, Team Guard SRL, Carlisle  Boulevard 8606, Oakland, COK 4607';
exec insertLibraryWishlistItem 'Un-Break My Heart','Icehouse, Trigonometry, Countess Mara, 21st Century Fox, Cavendish Avenue 4279, Fayetteville, TZA 7361';
exec insertLibraryWishlistItem 'Sway','None';
exec insertLibraryWishlistItem 'Let Me Love You','Chivas Regal, Physical Education, Lilli Ann, Boeing, Cato   Avenue 7207, Santa Ana, IRN 8308';
exec insertLibraryWishlistItem 'How you remind me','Smirnoff, Resource Program, Lee, Comcast, Elystan  Way 2950, Tallahassee, ABW 6438';
exec insertLibraryWishlistItem 'Sway','Blue Moon, Leadership, Old Navy, Zepter, Badric  Street 6939, Moreno Valley, FLK 4364';
exec insertLibraryWishlistItem 'YMCA','Corona, Leadership, Karen Kane, Demaco, Bellenden   Walk 3930, Jacksonville, GGY 3558';
exec insertLibraryWishlistItem 'Endless Summer','Absolut, Dramatics, Levis, CarMax, Clyde Avenue 7617, Phoenix, GMB 5666';
exec insertLibraryWishlistItem 'You are the one that I want','Budweiser, English IV, Converse, UPC, Elystan  Rue 7062, Zurich, KIR 7717';
exec insertLibraryWishlistItem 'Its not goodbye','Guinness, Geography, Bujo, Zepter, Balfe   Way 7783, Lisbon, VAT 3187';
exec insertLibraryWishlistItem '(Everything I Do) I Do It For You','Johnnie Walker, Modern Literature, Mossimo, Mars, Railroad Vale 5496, San Bernardino, NPL 1323';
exec insertLibraryWishlistItem 'YMCA','Guaranito, French, Rip Curl, Erickson, Blue Anchor  Avenue 7976, Minneapolis, MLT 0404';
exec insertLibraryWishlistItem 'Tonights The Night','Edelweiss, Earth Science, SABA, Team Guard SRL, Bempton   Walk 6778, Honolulu, SVN 0166';
exec insertLibraryWishlistItem 'Uptown Funk!','Tanqueray, Design and technology, Nudie Jeans, CarMax, Clarks  Vale 3947, San Diego, ALB 7230';
exec insertLibraryWishlistItem 'Lean on','Frooti, Language Arts, Calvin Klein, Coca-Cola Company, Belfort  Boulevard 5908, Hayward, TKM 2458';
exec insertLibraryWishlistItem 'Smooth','Tsingtao, American Literature, Rip Curl, Coca-Cola Company, Camera  Walk 6410, Irving, ANT 4727';
exec insertLibraryWishlistItem 'These boots are made for walking','Evian, Ecology, Cross Colours, ENEL, Kilner   Boulevard 4226, St. Louis, DZA 0833';
exec insertLibraryWishlistItem 'Blurred Lines','Orange Bird, Modern Literature, EMEL Fashion, Biolife Grup, Birkbeck  Rue 680, Bakersfield, RWA 2426';
exec insertLibraryWishlistItem 'Lets Get It On','Absolut, Accounting, Guess, Apple Inc., Arundel   Lane 4904, Minneapolis, JEY 8752';
exec insertLibraryWishlistItem 'We Belong Together','Evian, Leadership, Tommy Hilfinger, ENEL, Longmoore   Pass 5782, Los Angeles, MEX 2015';
exec insertLibraryWishlistItem 'Let Me Love You','SunnyD, Earth Science, Marchesa, Comcast, Beatty  Way 3349, Bakersfield, GNQ 5743';
exec insertLibraryWishlistItem 'Cheri cheri lady','Johnnie Walker, Earth Science, Avirex, Biolife Grup, Belgrave  Crossroad 7783, San Diego, SYR 1882';
exec insertLibraryWishlistItem 'Beat it','Keystone Light, LOGIC, Lilli Ann, Comcast, Thomas More   Tunnel 4949, Hayward, SYC 4867';
exec insertLibraryWishlistItem 'Kiss Kiss','Ciroc, Mathematics, TNT, ExxonMobil, Coleman  Crossroad 688, Springfield, GRD 4764';
exec insertLibraryWishlistItem 'Just one last dance','None';
exec insertLibraryWishlistItem 'Every Breath You Take','Frooti, Music, Baby Gap, Telekom, Heritage Hill 4284, Berlin, ITA 1531';
exec insertLibraryWishlistItem 'Cant touch this','None';
exec insertLibraryWishlistItem 'Uptown Funk!','Juicy Juice, Sociology, Mataano, Vodafone, Blomfield  Street 9455, Jersey City, VUT 1687';
exec insertLibraryWishlistItem 'How you remind me','Prigat, Science, Countess Mara, CarMax, Thoresby   Alley 7608, Lancaster, MWI 7202';
exec insertLibraryWishlistItem 'We Belong Together','Hennessy, Ecology, Loyandford, 21st Century Fox, Paris   Route 9025, Nashville, MAR 2783';
exec insertLibraryWishlistItem 'Wake me up before you gogo','Jack Daniels, Economics, Avirex, Amazon.com, Bel   Vale 9874, Detroit, SMR 2772';
exec insertLibraryWishlistItem 'Eye Of The Tiger','Chivas Regal, Health, Marchesa, AECOM, Cable    Pass 288, St. Louis, GIB 4144';
exec insertLibraryWishlistItem 'Andalouse','None';
exec insertLibraryWishlistItem 'How you remind me','Tsingtao, Modern Literature, Koalapop, Amazon.com, Carlisle  Avenue 9471, Lisbon, GRC 2050';
exec insertLibraryWishlistItem 'Despacito','Tanqueray, Music, C&A, BuzzFeed, Marina  Road 3337, Bellevue, PRY 7056';
exec insertLibraryWishlistItem 'Le Freak','None';
exec insertLibraryWishlistItem 'Listen to your heart','Skol, LOGIC, Nice Collective, Carrefour, Carnegie   Road 6325, Jacksonville, REU 7310';
exec insertLibraryWishlistItem 'Candyman','Guinness, Dramatics, JNCO, Leadertech Consulting, Cephas  Lane 3936, New York, MYT 2037';
exec insertLibraryWishlistItem 'Hero','Yanjing, Physical Education, Cherokee Inc., Mars, Church Crossroad 7312, Garland, TUN 8063';
exec insertLibraryWishlistItem 'Strongest','Bud Light, Handwriting, Mohito, Apple Inc., Fawn Avenue 8212, Indianapolis, TWN 7100';
exec insertLibraryWishlistItem 'Lemon','Grolsch, Language Arts, Andrew Marc, Team Guard SRL, Blean   Way 5246, Innsbruck, CHN 6215';
exec insertLibraryWishlistItem 'Nah neh nah','None';
exec insertLibraryWishlistItem 'You Light Up My Life','Absolut, Instrumental Music, Cherokee Inc., Boeing, Calverley  Street 9096, Henderson, BGR 7462';
exec insertLibraryWishlistItem 'Mack The Knife','Malibu, Speech, Izod, Metro Cash&Carry, Bigland  Street 7003, Fremont, AFG 0554';
exec insertLibraryWishlistItem 'Demons','Aquafina, Music, Angels Jeanswear, DynCorp, Archery  Pass 2698, Springfield, USA 3436';
exec insertLibraryWishlistItem 'Nah neh nah','Aquafina, Accounting, Dollie & Me, DynCorp, Clavell   Avenue 6473, Albuquerque, ZMB 3481';
exec insertLibraryWishlistItem 'Candyman','Mumm, Economics, Nudie Jeans, Team Guard SRL, Cave   Drive 2679, Irving, KHM 6252';
exec insertLibraryWishlistItem 'Getting over you','Nestlé Waters, Accounting, Nice Collective, ENEL, Clyde Alley 7602, New Orleans, VGB 6382';
exec insertLibraryWishlistItem 'Alors on dance','Z Lager, Modern Literature, Max Studio, AECOM, Ampton  Lane 8769, Phoenix, VEN 2563';
exec insertLibraryWishlistItem 'Tonights The Night','Prigat, Instrumental Music, Forever 21, Demaco, Camley   Tunnel 7001, Venice, COD 0305';
exec insertLibraryWishlistItem 'Jai HO','Aquafina, French, JNCO, Mars, Chesterfield  Way 144, San Francisco, GRC 7034';
exec insertLibraryWishlistItem 'Strongest','Icehouse, Accounting, Mossimo, DynCorp, Ashley Hill 2452, Colorado Springs, AFG 6708';
exec insertLibraryWishlistItem 'Bailando','Bacardi, Music, Bujo, Demaco, Gate   Crossroad 7998, San Diego, LAO 7061';
exec insertLibraryWishlistItem 'Demons','Chivas Regal, Accounting, Cherokee Inc., Mars, Tiptree   Crossroad 3419, Sacramento, BEN 5206';
exec insertLibraryWishlistItem 'Wake me up before you gogo','Prigat, Geography, Columbia Sportswear, Facebook, Longman   Boulevard 6779, Denver, MYS 4050';
exec insertLibraryWishlistItem 'Baila Morena','Edelweiss, Design and technology, Merc Clothing, Comodo, Chapel  Boulevard 4030, Rome, NAM 0203';
exec insertLibraryWishlistItem 'Uptown Funk!','None';
exec insertLibraryWishlistItem 'Let Me Love You','Juicy Juice, Leadership, Karen Kane, It Smart Group, Fairbairn  Boulevard 3841, Escondido, BLM 1546';
exec insertLibraryWishlistItem 'Party Rock Anthem','Guinness, Resource Program, Koalapop, Biolife Grup, Aberavon  Rue 920, Memphis, SGS 6436';
exec insertLibraryWishlistItem 'Party Rock Anthem','Absolut, Ancient Civilizations, Brooks Brothers, UPC, Ellerslie Vale 5192, Ontario, TTO 0205';
exec insertLibraryWishlistItem 'Its my life','None';
exec insertLibraryWishlistItem 'Cheri cheri lady','Absolut, Art, TNT, ENEL, Enford   Grove 3074, Louisville, PRY 1342';
exec insertLibraryWishlistItem 'You Light Up My Life','Frooti, Basic Math, SABA, BuzzFeed, Cloth  Boulevard 6407, Milwaukee, TGO 7224';
exec insertLibraryWishlistItem 'How Deep Is Your Love','Tsingtao, Speech, EMEL Fashion, ENEL, Adams  Walk 1190, San Jose, TUR 7414';
exec insertLibraryWishlistItem 'Tonights The Night','Jack Daniels, Ecology, Lilli Ann, UPC, Badric  Way 6368, Columbus, HKG 0570';
exec insertLibraryWishlistItem 'Party Rock Anthem','Duvel Golden Ale, Language Arts, Guess, Global Print, North Grove 9231, Oklahoma City, GUM 8446';
exec insertLibraryWishlistItem 'Wake me up','SunnyD, Ecology, Mohito, DynCorp, Mariner   Grove 715, Omaha, PSE 7872';
exec insertLibraryWishlistItem 'Blurred Lines','Corona, Economics, Cross Colours, Vodafone, Emden   Street 4751, Moreno Valley, MKD 2102';
exec insertLibraryWishlistItem 'Move to Miami','Aquafina, Basic Math, Tommy Hilfinger, DynCorp, Thoresby   Hill 7596, Omaha, ALA 6867';
exec insertLibraryWishlistItem 'Yeah!','Stella Artois, Basic Math, Nudie Jeans, Danone, Clarks  Road 9351, Bellevue, GLP 2745';
exec insertLibraryWishlistItem 'Wake me up before you gogo','Bud Light, Geography, TNT, Boeing, Oxford Way 7044, Garland, MWI 1861';
exec insertLibraryWishlistItem 'Jai HO','Brahma, American Literature, Real Gold, CarMax, Calshot   Alley 6293, London, HMD 0724';
exec insertLibraryWishlistItem 'These boots are made for walking','Edelweiss, Language Arts, Converse, Metro Cash&Carry, North Rue 7467, Dallas, UGA 1425';
exec insertLibraryWishlistItem 'Bette Davis Eyes','Tsingtao, American Literature, Rip Curl, AECOM, Adderley   Lane 4196, Huntsville, BWA 7144';
exec insertLibraryWishlistItem 'Endless Loves','Ciroc, French, Tommy Hilfinger, Amazon.com, Sherlock   Road 202, Toledo, GRL 4642';
exec insertLibraryWishlistItem 'Wake me up before you gogo','Smirnoff, American Literature, Mataano, Carrefour, Abbotswell  Walk 8946, Glendale, FJI 2352';
go;
set nocount off;
